module.exports = Object.freeze({
  NO_AUTHENT: 'NO_AUTHENT',

  NO_AUTHENT_METHOD: 'NO_AUTHENT_METHOD',

  OTP_HARDWARE: 'OTP_HARDWARE',

  OTP_SOFTWARE: 'OTP_SOFTWARE',

  OTP_TELE: 'OTP_TELE',

  PASSWORD: 'PASSWORD',
});
