module.exports = Object.freeze({
  DYNAMIC: 'DYNAMIC',
  NO_AUTHENT: 'NO_AUTHENT',
  NO_AUTHENT_METHOD: 'NO_AUTHENT_METHOD',
  OOB: 'OOB',
  OTP_HARDWARE: 'OTP_HARDWARE',
  OTP_SOFTWARE: 'OTP_SOFTWARE',
  OTP_TELE: 'OTP_TELE',
  PASSWORD: 'PASSWORD',
  STATIC: 'STATIC',
});
