module.exports = Object.freeze({
  ONE_EUROCOM: '1EUROCOM',
  THREE_DS: '3DS',
  THREE_DS_V2: '3DS_V2',
  APPLEPAY: 'APPLEPAY',
  ARP: 'ARP',
  BCMCMOBILE: 'BCMCMOBILE',
  MASTERPASS: 'MASTERPASS',
  NO_AUTHENT: 'NO_AUTHENT',
  NO_AUTHENT_METHOD: 'NO_AUTHENT_METHOD',
  NOT_SPECIFIED: 'NOT_SPECIFIED',
  PAYLIB: 'PAYLIB',
});
