module.exports = Object.freeze({
  TRANSACTION_INITIALIZED: '00',
  INVALID_MERCHANT_CONTRACT: '03',
  INVALID_TRANSACTION: '12',
  INCORRECT_FORMAT: '30',
  FRAUD_SUSPECTED: '34',
  DUPLICATED_TRANSACTION: '94',
  INTERNAL_ERROR: '99',
});
