module.exports = Object.freeze({
  ACCEPTED: '00',

  CARD_CEILING_EXCEEDED: '02',

  INVALID_MERCHANT_CONTRACT: '03',

  AUTHORIZATION_REFUSED: '05',

  PAN_BLOCKED: '11',

  INVALID_TRANSACTION: '12',

  INVALID_DATA: '14',

  CUSTOMER_CANCELLATION: '17',

  INCORRECT_FORMAT: '30',

  FRAUD_SUSPECTED: '34',

  PAYMENT_MEAN_EXPIRED: '54',

  MAX_ATTEMPTS_REACHED: '75',

  SERVICE_UNAVAILABLE: '90',

  DUPLICATED_TRANSACTION: '94',

  TIMEFRAME_EXCEEDED: '97',

  INTERNAL_ERROR: '99',
});
